#pragma once

#include <cstddef>
#include <cstdint>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

namespace exchange::fix {

constexpr char soh = '\x01';
constexpr std::string_view begin_string = "FIX.4.4";

struct Field {
    int tag {};
    std::string value;
};

class Message {
public:
    Message() = default;

    void add(int tag, std::string value);
    void set(int tag, std::string value);

    [[nodiscard]] std::optional<std::string_view>
    get(int tag) const noexcept;

    [[nodiscard]] bool contains(int tag) const noexcept;

    [[nodiscard]] const std::vector<Field>&
    fields() const noexcept;

private:
    std::vector<Field> fields_;
};

struct ParseResult {
    std::optional<Message> message;
    std::string error;

    [[nodiscard]] explicit operator bool() const noexcept {
        return message.has_value();
    }
};

enum class ExtractStatus {
    NeedMoreData,
    MessageReady,
    InvalidData
};

struct ExtractResult {
    ExtractStatus status {ExtractStatus::NeedMoreData};
    std::string wire_message;
    std::string error;
};

/*
 * Encode a FIX.4.4 message. The supplied Message contains the body/header
 * fields beginning with tag 35. Tags 8, 9, and 10 are generated by the
 * codec so BodyLength and CheckSum are always consistent.
 */
[[nodiscard]] std::string encode(const Message& message);

/*
 * Parse and validate one complete FIX.4.4 wire message, including
 * BeginString, BodyLength, and CheckSum.
 */
[[nodiscard]] ParseResult parse(std::string_view wire_message);

/*
 * Pull one complete FIX message from a TCP receive buffer. On success the
 * consumed bytes are removed from the buffer. Partial messages remain in
 * the buffer and return NeedMoreData.
 */
[[nodiscard]] ExtractResult extract_one(std::string& receive_buffer);

[[nodiscard]] std::optional<std::uint64_t>
parse_u64(std::string_view text) noexcept;

[[nodiscard]] std::optional<std::int64_t>
parse_i64(std::string_view text) noexcept;

[[nodiscard]] std::string utc_timestamp();

/* Human-readable rendering for terminal demos: SOH becomes '|'. */
[[nodiscard]] std::string printable(std::string_view wire_message);

}  // namespace exchange::fix